# Generated by Django 5.2.16 on 2026-07-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublote',
            name='ancho_escala',
        ),
        migrations.RemoveField(
            model_name='sublote',
            name='largo_escala',
        ),
        migrations.AddField(
            model_name='parcela',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Ancho en metros'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='largo',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Largo en metros'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='ubicacion',
            field=models.CharField(max_length=255, verbose_name='Ubicación'),
        ),
    ]
