# Generated by Django 6.0.7 on 2026-07-20 02:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('alerta', 'Alerta'), ('recomendacion', 'Recomendacion')], max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('info', 'Info'), ('advertencia', 'Advertencia'), ('critica', 'Critica')], default='info', max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('notificado_telegram', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('sublote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='parcelas.sublote')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alertas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['sublote', 'leida'], name='alertas_sublote_30fb59_idx')],
            },
        ),
    ]
