# Generated by Django 6.0.7 on 2026-07-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Chat ID de Telegram vinculado para recibir alertas críticas.', max_length=64, null=True),
        ),
    ]
